vit_linear:
    lr: 0.01                 # Suggested learning rate
    wd: 0.01                 # Suggested weight decay
    epochs: 100              # Total training epochs
    optimizer: 'sgd'         # Optimizer choice
    scheduler: 'multi_step'  # Scheduler for learning rate decay
    momentum: 0.9            # Momentum for SGD
    net_class: VITPrompt     # Class to use for VPT implementation
    batch_size: 32           # Batch size for training
    decay_epochs: [60, 80]   # Epochs at which to drop the learning rate
